language: python

sudo: false

cache:
  # Apparently if you override the install command that silently disables the
  # cache: pip support. See https://github.com/travis-ci/travis-ci/issues/3239
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
   - "2.7"
   - "3.4"
   - "pypy"
   - "pypy3"

install:
  # Before installation, we'll run ``pip wheel``, this will build wheels for
  # anything that doesn't already have one on PyPI.
  - pip wheel -r requirements.txt
  # Actually install our dependencies now, this will pull from the directory
  # that the first command placed the Wheels into.
  - pip install -r requirements.txt

script: true
